### ISSUE TITLE
Handling 'unused parameter' hints

### ISSUE THREAD

**Issue by jason0x43** [fannheyward/coc-pyright#107]
Pyright flags unused function parameters with a hint.

<img width="664" alt="Screen Shot 2020-10-24 at 12 11 12 PM" src="https://user-images.githubusercontent.com/1042866/97086601-404d2a80-15f2-11eb-9c77-1647b25cb612.png">

That is often helpful, but when you're trying to satisfy some library's API, you may want to include placeholders for parameters even if a function or method doesn't actually use them. An unused argument warning can be silenced by naming a parameter `_`, but that only works for one parameter. Names can be dundered (like `__name__`), but that feels like a hack, and doesn't work for keyword parameters. You could also use `*arg` and `**kwargs`, but is a bit less clear that having placeholders.

According to [this](https://github.com/microsoft/pyright/issues/1118#issuecomment-715634376), the Pyright language server tags unused parameter hints in some way, and the LSP client can tell Pyright that it doesn't support this tag to prevent Pyright from sending these hints. Possibly coc-pyright could provide an option to disable unused argument hints.

**Comment by fannheyward** [comment]
Fixed in https://github.com/neoclide/coc.nvim/pull/2538, upgrade to latest coc.nvim and set `diagnostic.showUnused` to `false`.

**Comment by lucatpa** [comment]
Is there any way to special-case this to only show the parameter grayed out without showing any error information? It seems like a good idea to have a visual hint that a variable is unused but having an error produces a lot of noise. This is what Visual Code seems to do according to this pyright issue where this problem was brought up by several people: https://github.com/microsoft/pyright/issues/1118

**Comment by lucatpa** [comment]
Also, this new `diagnostic.showUnused` also disable real unused **variables**, which is a different beast, as there is hardly a good reason for wanting to keep an unused variable, while, as pointed out here, function parameters are sometimes outside our control, so there are very good reasons to having some of those you can't avoid. So I very much want to get hints (as warnings/errors) about unused variables.

**Comment by fannheyward** [comment]
@lucatpa Upgrade your coc.nvim, the latest coc can gray out the unused var without an error/warning.

**Comment by lucatpa** [comment]
Thanks @fannheyward!

I just upgraded (using the `release` branch) and I'm still getting the hint window

![image](https://user-images.githubusercontent.com/84440327/127297353-dde8b455-1bb7-4df2-88d9-88d9ddc3b694.png)

Is this available only on `master` or am I misunderstanding what I should expect?

**Comment by fannheyward** [comment]
@lucatpa the unused var will be grayed out, but if you put your cursor on it, the hint message will still showing. It's the expected behavior.

**Comment by lucatpa** [comment]
I'm caught in the middle of different opinions here, because [pyright developers say this should only be a syntax highlight hint and no other visual indication should be shown](https://github.com/microsoft/pyright/issues/1118#issuecomment-887715415). For parameters of functions that are fulfilling some API this leaves users in a bad position where they have to chose to have visual noise for irrelevant (and unavoidable) noise (having a popup and a mark in the line) or completely disabling all unused variables hinting.

So is there no way to reconcile both projects views on this one? Should I just give up? And I'm not being cynical here, I'm truly hugely thankful to both projects because they make my life so much easier, this is only a tiny nuance. I just want to avoid wasting your and my time if there will be no agreement between both projects.

**Comment by fannheyward** [comment]
For example:

```py
#!/usr/bin/env python3

def foo(name):
    """docstring for foo"""
    pass
```

<img width="337" alt="截屏2021-07-29 上午10 42 02" src="https://user-images.githubusercontent.com/345274/127423254-c5c24b58-bf2d-46e1-b55c-9bf0b27fb703.png">

The `name` parameter is not used. coc will make it gray out, but it's still a diagnostic because Pyright published this:

```json
{
    "range": {
        "start": {
            "line": 2,
            "character": 8
        },
        "end": {
            "line": 2,
            "character": 12
        }
    },
    "message": "\"name\" is not accessed",
    "severity": 4,
    "source": "Pyright",
    "tags": [
        1
    ]
}
```

The diagnostic level is Hint. coc will sign it as `>>` on signcolumn.

<img width="345" alt="截屏2021-07-29 上午10 49 26" src="https://user-images.githubusercontent.com/345274/127423840-7aad9f73-cc7b-4216-830d-344cda5710ac.png">

In VSCode, `name` also be grayed out, if you put your cursor on it, you can get the diagnostic message.

I've know your problem, IMO the 'unused parameter' hint is a diagnostic, both coc/VSCode will gray out it, but in coc you will still get the sign noise. You can set `"diagnostic.hintSign": ""` to disable the sign, but it's still a diagnostic in `:CocDiagnostics`.

> I'm not being cynical here

It's OK here.

**Comment by lucatpa** [comment]
OK, I see. Thanks for getting getting involved in the pyright issues. I think the real solution would be to provide a way to ignore unused parameters for certain functions, as stated in pyright issues, because the problem here (or to me) is getting the editor even notifying me, in any way, noisy or not, about something that is expected and I can't possibly fix. Even a gray-out would still be noise, more manageable but noise.

I will try the `"diagnostic.hintSign": ""`, this might help to reduce the noise. Thanks!

**Comment by lithammer** [comment]
Personally, I didn't have signs enabled, but did have virtual text enabled. So my solution was this:

```json
{"diagnostic.virtualTextLevel": "information"}
```

However I'm unsure what other consequences there are for this. I might be missing something useful.

**Comment by duongdominhchau** [comment]
This may be a non-solution to others, but personally I "fixed" this by disabling the reporting of unused var from Pyright and use Ruff instead as Ruff can be configured to only report unused vars not starting with `_`. This way I don't lose the ability to recognize unused variables, but can still suppress it when needed.

**Comment by eullerborges** [comment]
Note that you also need `"diagnostic.level": "information"` on `pyrightconfig.json` for the solution proposed by `duongdominchau` to work. Also, you'll want to add a dummy variable regex (`dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"`) to the ruff configuration (`~/.ruff.toml`).
