### ISSUE TITLE
Pylint not working

### ISSUE THREAD

**Issue by sabah1994** [fannheyward/coc-pyright#892]
Pylint was previously working but I have only realised today that it stopped. It must've been some update. 
These are the pyright related setting in my settings.json file.

    "python.formatting.provider": "black",
    "python.formatting.blackPath": "~/vim_venv/bin/black",
    "python.linting.enabled": true,
    "python.analysis.typeCheckingMode": "off",
    "python.linting.pylintEnabled": true,

I have also tried setting "python.linting.pylintPath" in a venv (where i Installed pylint) also installed in the currently activated venv but no luck.

I couldn't find any documentation around how to debug the issue.  

**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.293 with Pyright 1.1.295

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /home/sabah/Desktop/test/python
Using python from /home/sabah/Desktop/test/python/venv/bin/python

[Info  - 21:51:38.161] Pyright language server 1.1.295 starting
[Info  - 21:51:38.161] Server root directory: /home/sabah/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 21:51:38.164] Starting service instance "python"
[Info  - 21:51:38.174] Starting service instance "<default>"
[Info  - 21:51:38.177] No configuration file found.
[Info  - 21:51:38.177] No pyproject.toml file found.
[Info  - 21:51:38.177] Setting pythonPath for service "python": "/home/sabah/Desktop/test/python/venv/bin/python"
[Warn  - 21:51:38.180] stubPath /home/sabah/Desktop/test/python/typings is not a valid directory.
[Info  - 21:51:38.200] Assuming Python version 3.10
[Info  - 21:51:38.200] Assuming Python platform Linux
[Info  - 21:51:38.254] Searching for source files
[Info  - 21:51:38.256] Auto-excluding /home/sabah/Desktop/test/python/database/venv
[Info  - 21:51:38.256] Auto-excluding /home/sabah/Desktop/test/python/my_venv
[Info  - 21:51:38.256] Auto-excluding /home/sabah/Desktop/test/python/playwright/venv
[Info  - 21:51:38.257] Auto-excluding /home/sabah/Desktop/test/python/scrapper/tutorial/venv
[Info  - 21:51:38.257] Auto-excluding /home/sabah/Desktop/test/python/scrapper/venv
[Info  - 21:51:38.257] Auto-excluding /home/sabah/Desktop/test/python/venv
[Info  - 21:51:38.261] Found 26 source files
[Info  - 21:51:38.264] No pyproject.toml file found.
[Info  - 21:51:38.264] Setting pythonPath for service "<default>": "/home/sabah/Desktop/test/python/venv/bin/python"
[Warn  - 21:51:38.264] stubPath typings is not a valid directory.
[Info  - 21:51:38.285] Assuming Python version 3.10
[Info  - 21:51:38.285] Assuming Python platform Linux
[Info  - 21:51:38.316] Searching for source files
[Info  - 21:51:38.316] No source files found.

**Comment by sabah1994** [comment]
Actually I had a little luck with this command :CocCommand workspace.showOutput and select coc-pyright-linting
I can see it's running but it doesn't show errors and at times it's buggy.
e.g take this file for example
```
from anotherTest import addTwo

def someFun(speed):
    """
    hello
    """
    if speed < 50:
        return "Hi"
    return None

helo = someFun()
print(len(helo))


def anotherFunc(arg1):
    foo = 3
    bar = ""
    if foo > 1 and foo < 2:
        return bar
```

This is the terminal output of Pylint on this file:
```
************* Module test
test.py:4:0: C0103: Function name "someFun" doesn't conform to snake_case naming style (invalid-name)
test.py:12:7: E1120: No value for argument 'speed' in function call (no-value-for-parameter)
test.py:16:0: C0116: Missing function or method docstring (missing-function-docstring)
test.py:16:0: C0103: Function name "anotherFunc" doesn't conform to snake_case naming style (invalid-name)
test.py:17:4: C0104: Disallowed name "foo" (disallowed-name)
test.py:18:4: C0104: Disallowed name "bar" (disallowed-name)
test.py:19:7: R1716: Simplify chained comparison between the operands (chained-comparison)
test.py:16:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
test.py:16:16: W0613: Unused argument 'arg1' (unused-argument)
test.py:2:0: W0611: Unused addTwo imported from anotherTest (unused-import)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)

```

And here is the output of  :CocCommand workspace.showOutput and select coc-pyright-linting
```
Using python from /home/sabah/Desktop/test/python/venv/bin/python

########## active linter: pylint
########## Run linter pylint:
{"execPath":"/home/sabah/vim_venv/bin/pylint","args":["--msg-template='{line},{column},{category},{symbol}:{msg}'","--exit-zero","--reports=n","--output-format=text","--from-stdin","/home/sabah/Desktop/test/python/test.py"],"product":1}

########## Linting Output - pylint ##########
************* Module test
1,0,convention,missing-module-docstring:Missing module docstring
```

It doesn't even throw error on when calling someFun() without expected argument. 
How can I fix this?

**Comment by sabah1994** [comment]
I looked at few other issues and for some people setting ```python.linting.pylintUseMinimalCheckers``` to false fixed the issue. I tried it but it doesn't do anything for me

**Comment by fannheyward** [comment]
Should be fixed with coc-pyright v1.1.295.

**Comment by sabah1994** [comment]
Did CocUpdate it's not picking up latest version.
CocUpdate output:
```- ✓ coc-pyright Current version 1.1.293 is up to date.```

**Comment by fannheyward** [comment]
@sabah1994 `CocUpdate` again, I did miss the `npm publish`.

**Comment by sabah1994** [comment]
does pylint not respect diagnostic.level?
I have set mine to  ``  "diagnostic.level": "hint" ``
but I get still get info diagnostics from it?

**Comment by sabah1994** [comment]
I specified  ```"python.linting.pylintPath" ``` to venv x and then I activate venv y and enter nvim, pylint attempts to use python of venv x and I get error on modules not found.
Fix for me is I have to remove ```PylintPath"  and install pylint in venv y and then it works. Does this mean I have to install pylint in every venv that I am working with?

**Comment by fannheyward** [comment]
> pylint attempts to use python of venv x and I get error on modules not found

@sabah1994 what's your `:CocCommand workspace.showOutput coc-pyright-linting`?

**Comment by sabah1994** [comment]
```Using python from /home/sabah/Desktop/test/python/venv/bin/python

########## active linter: pylint
########## Run linter pylint:
{"execPath":"/home/sabah/vim_venv/bin/pylint","args":["-d","C0114,C0116","--msg-template='{line},{column},{category},{symbol}:{msg}'","--exit-zero","--reports=n","--output-format=text","--from-stdin","/home/sabah/Desktop/test/python/test.py"],"product":1}

########## Linting Output - pylint ##########
************* Module test
1,0,error,import-error:Unable to import 'Flask'
6,7,refactor,chained-comparison:Simplify chained comparison between the operands
1,0,warning,unused-import:Unused import Flask

------------------------------------------------------------------
Your code has been rated at 1.25/10 (previous run: 1.25/10, +0.00)
```
Python on line one does have Flask installed.

**Comment by fannheyward** [comment]
> /home/sabah/vim_venv/bin/pylint

Does this the correct pylint path?

**Comment by sabah1994** [comment]
Yes

**Comment by fannheyward** [comment]
`/home/sabah/Desktop/test/python/test.py` is your project file, and `pylint` is from your `vim_venv`, you don't need to install pylint in your every project venv now.

**Comment by sabah1994** [comment]
Yes I do, because it doesn't do the linting properly. 
If I install a package in another venv which I have activated, it doesn't look for packages there. 
To recreate the issue.
1) create a separate venv for pylint
```
    rm -rf ~/vim_venv
    python3 -m venv ~/vim_venv
    source ~/vim_venv/bin/activate
    pip install pylint
```
2) Set pylint path to above venv
```
    "python.linting.pylintPath": "~/vim_venv/bin/pylint",
```
3) Create another env for your project and install a package
```
cd ~/test
python3 -m venv venv
source venv/bin/activate
pip install flask
```
4) source project venv and enter vim and try importing flask
```
cd ~/test
source venv/bin/activate
echo from flask import Flask >> another_test.py
```
Open above file and you will get error flask not found

**Comment by fannheyward** [comment]
Does `~/vim_venv/bin/pylint another_test.py` in your test project work? I don't think this can work.

**Comment by fannheyward** [comment]
I've tested follow your steps,  `~/vim_venv/bin/pylint another_test.py` reports `Unable to import 'flask' (import-error)`.

**Comment by sabah1994** [comment]
exactly, even tho it uses python from venv which has flask installed it can't import it.
 It looks from packages in  ```"python.linting.pylintPath"```

**Comment by fannheyward** [comment]
It's pylint behavior.

**Comment by sabah1994** [comment]
so the only work around is to install pylint in every project venv I create
